//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerEngine.SMSServiceADP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.adpdigital.com/services/messaging", ConfigurationName="SMSServiceADP.JaxRpcMessagingService")]
    public interface JaxRpcMessagingService {
        
        // CODEGEN: Parameter 'messages' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sendMultipleReturn")]
        TaskManagerEngine.SMSServiceADP.sendMultipleResponse sendMultiple(TaskManagerEngine.SMSServiceADP.sendMultipleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getBalanceReturn")]
        TaskManagerEngine.SMSServiceADP.BalanceResult getBalance(string userName, string password, short facilityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="changePasswordReturn")]
        short changePassword(string userName, string currentPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getStatusReturn")]
        short getStatus(long messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="receiveReturn")]
        TaskManagerEngine.SMSServiceADP.ReceiveResult receive(string userName, string password, string shortNumber, long start, int maxSize);
        
        // CODEGEN: Parameter 'destNo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sendReturn")]
        TaskManagerEngine.SMSServiceADP.sendResponse send(TaskManagerEngine.SMSServiceADP.sendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="reportReturn")]
        TaskManagerEngine.SMSServiceADP.ReportResult report(string userName, string password, string shortNumber, string fromClientId, string clientId, string fromId, string id, int maxSize);
        
        // CODEGEN: Parameter 'ids' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="statusReportReturn")]
        TaskManagerEngine.SMSServiceADP.statusReportResponse statusReport(TaskManagerEngine.SMSServiceADP.statusReportRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class MultiAddressMessageObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentField;
        
        private short encodingField;
        
        private string[] phoneNumbersField;
        
        private string[] clientIdsField;
        
        private System.DateTime dueTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
                this.RaisePropertyChanged("encoding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] phoneNumbers {
            get {
                return this.phoneNumbersField;
            }
            set {
                this.phoneNumbersField = value;
                this.RaisePropertyChanged("phoneNumbers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] clientIds {
            get {
                return this.clientIdsField;
            }
            set {
                this.clientIdsField = value;
                this.RaisePropertyChanged("clientIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime dueTime {
            get {
                return this.dueTimeField;
            }
            set {
                this.dueTimeField = value;
                this.RaisePropertyChanged("dueTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class OutgoingMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string clientIdField;
        
        private short statusField;
        
        private string toField;
        
        private System.DateTime timeField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string clientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("clientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public short status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("to");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class StatusReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private short statusField;
        
        private string clientIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string clientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("clientId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class MessageObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int chunkField;
        
        private string clientIdField;
        
        private string contentField;
        
        private short encodingField;
        
        private long idField;
        
        private string phoneNumberField;
        
        private short statusField;
        
        private System.Nullable<System.DateTime> timeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int chunk {
            get {
                return this.chunkField;
            }
            set {
                this.chunkField = value;
                this.RaisePropertyChanged("chunk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string clientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("clientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public short encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
                this.RaisePropertyChanged("encoding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public short status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class IncomingMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentField;
        
        private short encodingField;
        
        private string fromField;
        
        private long idField;
        
        private object requestField;
        
        private short statusField;
        
        private System.Nullable<System.DateTime> timeField;
        
        private string toField;
        
        private short typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
                this.RaisePropertyChanged("encoding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("from");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public object request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
                this.RaisePropertyChanged("request");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public short status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("to");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public short type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReportResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusReportResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceiveResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BalanceResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public abstract partial class Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class ReportResult : Result {
        
        private OutgoingMessage[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("messages", IsNullable=false)]
        public OutgoingMessage[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class StatusReportResult : Result {
        
        private StatusReport[] reportField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("report", IsNullable=false)]
        public StatusReport[] report {
            get {
                return this.reportField;
            }
            set {
                this.reportField = value;
                this.RaisePropertyChanged("report");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class ReceiveResult : Result {
        
        private IncomingMessage[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("messages", IsNullable=false)]
        public IncomingMessage[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class BalanceResult : Result {
        
        private long balanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("balance");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.adpdigital.com/services/messaging")]
    public partial class SendResult : Result {
        
        private long[] idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", IsNullable=false)]
        public long[] id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMultiple", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class sendMultipleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=2)]
        public string shortNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=3)]
        public string sourcePort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=4)]
        public string destPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=5)]
        public short messageType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=6)]
        public bool longSupported;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute("messages")]
        public TaskManagerEngine.SMSServiceADP.MultiAddressMessageObject[] messages;
        
        public sendMultipleRequest() {
        }
        
        public sendMultipleRequest(string userName, string password, string shortNumber, string sourcePort, string destPort, short messageType, bool longSupported, TaskManagerEngine.SMSServiceADP.MultiAddressMessageObject[] messages) {
            this.userName = userName;
            this.password = password;
            this.shortNumber = shortNumber;
            this.sourcePort = sourcePort;
            this.destPort = destPort;
            this.messageType = messageType;
            this.longSupported = longSupported;
            this.messages = messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMultipleResponse", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class sendMultipleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public TaskManagerEngine.SMSServiceADP.SendResult sendMultipleReturn;
        
        public sendMultipleResponse() {
        }
        
        public sendMultipleResponse(TaskManagerEngine.SMSServiceADP.SendResult sendMultipleReturn) {
            this.sendMultipleReturn = sendMultipleReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class sendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=2)]
        public string sourceNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("destNo")]
        public string[] destNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=4)]
        public string sourcePort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=5)]
        public string destPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("clientId")]
        public string[] clientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=7)]
        public short messageType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=8)]
        public short encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=9)]
        public bool longSupported;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=10)]
        public System.DateTime dueTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=11)]
        public string content;
        
        public sendRequest() {
        }
        
        public sendRequest(string userName, string password, string sourceNo, string[] destNo, string sourcePort, string destPort, string[] clientId, short messageType, short encoding, bool longSupported, System.DateTime dueTime, string content) {
            this.userName = userName;
            this.password = password;
            this.sourceNo = sourceNo;
            this.destNo = destNo;
            this.sourcePort = sourcePort;
            this.destPort = destPort;
            this.clientId = clientId;
            this.messageType = messageType;
            this.encoding = encoding;
            this.longSupported = longSupported;
            this.dueTime = dueTime;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendResponse", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class sendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public TaskManagerEngine.SMSServiceADP.SendResult sendReturn;
        
        public sendResponse() {
        }
        
        public sendResponse(TaskManagerEngine.SMSServiceADP.SendResult sendReturn) {
            this.sendReturn = sendReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="statusReport", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class statusReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=2)]
        public string shortNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=3)]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("ids")]
        public long[] ids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("clientIds")]
        public string[] clientIds;
        
        public statusReportRequest() {
        }
        
        public statusReportRequest(string userName, string password, string shortNumber, string type, long[] ids, string[] clientIds) {
            this.userName = userName;
            this.password = password;
            this.shortNumber = shortNumber;
            this.type = type;
            this.ids = ids;
            this.clientIds = clientIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="statusReportResponse", WrapperNamespace="http://www.adpdigital.com/services/messaging", IsWrapped=true)]
    public partial class statusReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.adpdigital.com/services/messaging", Order=0)]
        public TaskManagerEngine.SMSServiceADP.StatusReportResult statusReportReturn;
        
        public statusReportResponse() {
        }
        
        public statusReportResponse(TaskManagerEngine.SMSServiceADP.StatusReportResult statusReportReturn) {
            this.statusReportReturn = statusReportReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JaxRpcMessagingServiceChannel : TaskManagerEngine.SMSServiceADP.JaxRpcMessagingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JaxRpcMessagingServiceClient : System.ServiceModel.ClientBase<TaskManagerEngine.SMSServiceADP.JaxRpcMessagingService>, TaskManagerEngine.SMSServiceADP.JaxRpcMessagingService {
        
        public JaxRpcMessagingServiceClient() {
        }
        
        public JaxRpcMessagingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JaxRpcMessagingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JaxRpcMessagingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JaxRpcMessagingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaskManagerEngine.SMSServiceADP.sendMultipleResponse TaskManagerEngine.SMSServiceADP.JaxRpcMessagingService.sendMultiple(TaskManagerEngine.SMSServiceADP.sendMultipleRequest request) {
            return base.Channel.sendMultiple(request);
        }
        
        public TaskManagerEngine.SMSServiceADP.SendResult sendMultiple(string userName, string password, string shortNumber, string sourcePort, string destPort, short messageType, bool longSupported, TaskManagerEngine.SMSServiceADP.MultiAddressMessageObject[] messages) {
            TaskManagerEngine.SMSServiceADP.sendMultipleRequest inValue = new TaskManagerEngine.SMSServiceADP.sendMultipleRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.shortNumber = shortNumber;
            inValue.sourcePort = sourcePort;
            inValue.destPort = destPort;
            inValue.messageType = messageType;
            inValue.longSupported = longSupported;
            inValue.messages = messages;
            TaskManagerEngine.SMSServiceADP.sendMultipleResponse retVal = ((TaskManagerEngine.SMSServiceADP.JaxRpcMessagingService)(this)).sendMultiple(inValue);
            return retVal.sendMultipleReturn;
        }
        
        public TaskManagerEngine.SMSServiceADP.BalanceResult getBalance(string userName, string password, short facilityId) {
            return base.Channel.getBalance(userName, password, facilityId);
        }
        
        public short changePassword(string userName, string currentPassword, string newPassword) {
            return base.Channel.changePassword(userName, currentPassword, newPassword);
        }
        
        public short getStatus(long messageId) {
            return base.Channel.getStatus(messageId);
        }
        
        public TaskManagerEngine.SMSServiceADP.ReceiveResult receive(string userName, string password, string shortNumber, long start, int maxSize) {
            return base.Channel.receive(userName, password, shortNumber, start, maxSize);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaskManagerEngine.SMSServiceADP.sendResponse TaskManagerEngine.SMSServiceADP.JaxRpcMessagingService.send(TaskManagerEngine.SMSServiceADP.sendRequest request) {
            return base.Channel.send(request);
        }
        
        public TaskManagerEngine.SMSServiceADP.SendResult send(string userName, string password, string sourceNo, string[] destNo, string sourcePort, string destPort, string[] clientId, short messageType, short encoding, bool longSupported, System.DateTime dueTime, string content) {
            TaskManagerEngine.SMSServiceADP.sendRequest inValue = new TaskManagerEngine.SMSServiceADP.sendRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.sourceNo = sourceNo;
            inValue.destNo = destNo;
            inValue.sourcePort = sourcePort;
            inValue.destPort = destPort;
            inValue.clientId = clientId;
            inValue.messageType = messageType;
            inValue.encoding = encoding;
            inValue.longSupported = longSupported;
            inValue.dueTime = dueTime;
            inValue.content = content;
            TaskManagerEngine.SMSServiceADP.sendResponse retVal = ((TaskManagerEngine.SMSServiceADP.JaxRpcMessagingService)(this)).send(inValue);
            return retVal.sendReturn;
        }
        
        public TaskManagerEngine.SMSServiceADP.ReportResult report(string userName, string password, string shortNumber, string fromClientId, string clientId, string fromId, string id, int maxSize) {
            return base.Channel.report(userName, password, shortNumber, fromClientId, clientId, fromId, id, maxSize);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaskManagerEngine.SMSServiceADP.statusReportResponse TaskManagerEngine.SMSServiceADP.JaxRpcMessagingService.statusReport(TaskManagerEngine.SMSServiceADP.statusReportRequest request) {
            return base.Channel.statusReport(request);
        }
        
        public TaskManagerEngine.SMSServiceADP.StatusReportResult statusReport(string userName, string password, string shortNumber, string type, long[] ids, string[] clientIds) {
            TaskManagerEngine.SMSServiceADP.statusReportRequest inValue = new TaskManagerEngine.SMSServiceADP.statusReportRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.shortNumber = shortNumber;
            inValue.type = type;
            inValue.ids = ids;
            inValue.clientIds = clientIds;
            TaskManagerEngine.SMSServiceADP.statusReportResponse retVal = ((TaskManagerEngine.SMSServiceADP.JaxRpcMessagingService)(this)).statusReport(inValue);
            return retVal.statusReportReturn;
        }
    }
}
